#   3. Создайте собственный класс-исключение, который должен проверять содержимое списка на наличие только чисел.
#   Проверить работу исключения на реальном примере. Запрашивать у пользователя данные и заполнять список необходимо
#   только числами. Класс-исключение должен контролировать типы данных элементов списка.
#
#       Примечание:     длина списка не фиксирована. Элементы запрашиваются бесконечно, пока пользователь сам не остановит
#                       работу скрипта, введя, например, команду «stop». При этом скрипт завершается, сформированный список
#                       с числами выводится на экран.

#       Подсказка:      для этого задания примем, что пользователь может вводить только числа и строки. Во время ввода
#                       пользователем очередного элемента необходимо реализовать проверку типа элемента. Вносить его в список,
#                       только если введено число. Класс-исключение должен не позволить пользователю ввести текст (не число)
#                       и отобразить соответствующее сообщение. При этом работа скрипта не должна завершаться.

class Err:
    def __init__(self, *args):
        self.my_list = []

    def my_input(self):

        # self.my_list = [int(i) for i in input('Введите значения через пробел ').split()]
        # val = int(input('Введите значения и нажимайте Enter - '))
        # self.my_list.append(val)
        while True:
            try:
                val = int(input('Введите значения  - '))
                self.my_list.append(val)
                print(f'Мой список - {self.my_list} \n ')
            except:
                print(f'Введенное значение не является числом')
                usl = input(f'Если хотите ввести значение повторно - нажмите "Y". Для выхода нажмите "N".')
                if usl == 'Y' or usl == 'y':
                    print(try_except.my_input())
                elif usl == 'N' or usl == 'n':
                    return f'Вы вышли!'
                else:
                    return f'Вы вышли!'

try_except = Err(1)
print(try_except.my_input())